### ISSUE TITLE
.nam to .nam.stripe conversion failure

### ISSUE THREAD

**Issue by rlnilsen** [ejona86/taus#16]
A `.nam` file containing `0xd,0xa` will mess up the conversion to `.nam.stripe`. The issue can be fixed by adding `-v BINMODE=3` to the relevant `awk` command in `Makefile`. This probably also applies to the reverse conversion.

Edit:
This was on Win10 x64 1909, set up as instructed under "How to build" in `README.md`.

I also created PR #17 for this issue, mostly for my own learning experience. You can use it if you want.

**Comment by ejona86** [comment]
Fixed by #17.

I'm a bit surprised I've not had any other interpreted-as-text Windows issues. Thanks for tracking down the issue and fixing. I know they can be annoying to debug, especially with how much scripting this project uses.

**Comment by rlnilsen** [comment]
It was an insignificant use of time compared to what is saved by this framework for creating Tetris mods. Thank _you_!
