### ISSUE TITLE
Unable to get patch to work in Retroarch

### ISSUE THREAD

**Issue by yllekz** [ejona86/taus#36]
Hi folks, I've tried multiple times to get taus to work in retroarch on the Wii or on a PC, and it always results in the game immediately crashing back to either the Retroarch main menu or taking down the system entirely. FCEUmm seems to be the only core that will even attempt to load the game + patch (all others crash immediately), but that's not saying much because it either does not apply the patch or it crashes.

I was checking logs and it almost seems as if retroarch is warning about needing disksys.rom when using taus 1.5.0 specifically. Was that at any point part of this patch as a dependency? The instructions only state to use a US Tetris ROM.

Seems to be happening in both 1.3.0 and 1.5.0. Has anyone had any success getting this to run in Retroarch?

**Comment by ejona86** [comment]
I didn't have any problem using Nestopia UE 93 core on Linux and Retroarch 1.14.0. I pre-applied the IPS though, so I just loaded a NES in Retroarch. You can use flips or https://www.romhacking.net/patch/ to apply the IPS. It shouldn't have any dependencies on top of normal Tetris.

**Comment by yllekz** [comment]
I got it working via FCEUX TX on Wii. Not sure what it is, but I guess the issue seems to be oddly specific to the Wii version of RetroArch (I don't have this problem on RetroArch 3DS, IPS auto-patching works just fine there). Guess it's just one of those things.
