### ISSUE TITLE
but how do you open it?

### ISSUE THREAD

**Issue by beatmakerofficial** [ejona86/taus#37]
????????????????????????

**Comment by beatmakerofficial** [comment]
btw im using FCEUX on windows

**Comment by ejona86** [comment]
You need to apply the IPS to the Tetris NES ROM. Generally folks use flips or https://www.romhacking.net/patch/

**Comment by beatmakerofficial** [comment]
OK thanks. One more thing, there are a bunch of .ips files. Should I just patch it with one, and then patch the new rom with the next one, and so on?

**Comment by ejona86** [comment]
Yep, if you want two player and handicap, apply one ips, then apply the other ips to the result.

**Comment by beatmakerofficial** [comment]
Alr thanks
