### ISSUE TITLE
Feature request: Endless mode

### ISSUE THREAD

**Issue by voltrevo** [ejona86/taus#38]
Love these mods.

Could you add an endless mode? Just disable level-up :).

**Comment by ejona86** [comment]
That sounds like game genie code `XVVOVLVV`. If you want to create a patched ROM or IPS, you can use something like:
https://www.romhacking.net/utilities/1054/
https://www.romhacking.net/utilities/1484/

**Comment by voltrevo** [comment]
Perfect! Works with these mods too. Cheers.
